name: so_boleto
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.4
  go_router: ^12.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: 0.19.0
  json_annotation: ^4.8.1
  
dev_dependencies:
  build_runner: ^2.4.7
  flutter_test: 
     sdk: flutter
  flutter_lints: ^3.0.1 
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: AMX
      fonts:
        - asset: assets/fonts/AMX-Black.ttf
        - asset: assets/fonts/AMX-BlackItalic.ttf
        - asset: assets/fonts/AMX-Bold.ttf
        - asset: assets/fonts/AMX-BoldItalic.ttf
        - asset: assets/fonts/AMX-Light.ttf
        - asset: assets/fonts/AMX-LightItalic.ttf
        - asset: assets/fonts/AMX-Medium.ttf
        - asset: assets/fonts/AMX-MediumItalic.ttf
        - asset: assets/fonts/AMX-Regular.ttf
    
    - family: Old-Stamper
      fonts:
        - asset: assets/fonts/Old-Stamper.ttf
    
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto-Black.ttf
        - asset: assets/fonts/roboto-BlackItalic.ttf
        - asset: assets/fonts/roboto-Bold.ttf
        - asset: assets/fonts/roboto-BoldItalic.ttf
        - asset: assets/fonts/roboto-Medium.ttf
        - asset: assets/fonts/roboto-MediumItalic.ttf
        - asset: assets/fonts/roboto-Regular.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: pt
  arb_dir: lib/core/l10n/arb
  output_dir: lib/core/l10n/generated
  use_deferred_loading: false
